config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  resources :categories do
    resources :products do
      resources :reviews
    end
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, :only => [:show]
  root 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  
  validates :name, uniqueness: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reviews

  validates :title, presence: true
  validates :price, presence: true, format: { :with => /\A\d+(?:\.\d{0,2})?\z/ }
  validates :description, presence: true

  def average_rating
    self.reviews.average(:rating).round(2) if self.reviews.count != 0
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  
  validates :content, presence: true
  validates :rating, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :firstname, presence: true
  validates :lastname, presence: true

  has_many :reviews
  has_many :products

  def member_since
    created_at.strftime("%B %e, %Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  before_action :admin_user, only: [:update, :create, :new, :edit, :destroy]
  
  expose(:categories)
  expose(:category)
  expose(:product) { Product.new }

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    self.category = Category.new(category_params)

    if category.save
      redirect_to category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if category.update(category_params)
      redirect_to category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
    
    def admin_user
      redirect_to(new_user_session_path) unless current_user.admin?
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:update, :create, :destroy]
  before_action :correct_user, only: [:edit, :update]

  expose(:category)
  expose(:products)
  expose(:product)
  expose(:review) { Review.new }
  expose_decorated(:reviews, ancestor: :product)

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    self.product = Product.new(product_params)
    self.product.user_id = current_user.id

    if product.save
      category.products << product
      redirect_to category_product_url(category, product), notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if self.product.update(product_params)
      redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /products/1
  def destroy
    product.destroy
    redirect_to category_url(product.category), notice: 'Product was successfully destroyed.'
  end

  private

    def product_params
      params.require(:product).permit(:title, :description, :price, :category_id)
    end

    def correct_user
      if !current_user.nil? and current_user.products.find_by(id: params[:id]).nil?
        flash[:error] = 'You are not allowed to edit this product.'
        redirect_to category_product_url(category, product)
      end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

  def sign_up_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :current_password)
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  expose(:review)
  expose(:product)

  def edit
  end

  def create
    self.review = Review.new(review_params)
    self.review.user_id = current_user.id

    if review.save
      product.reviews << review
      redirect_to category_product_url(product.category, product), notice: 'Review was successfully created.'
    else
      redirect_to category_product_url(product.category, product), alert: 'Invalid Review content or rating.'
    end
  end

  def destroy
    review.destroy
    redirect_to category_product_url(product.category, product), notice: 'Review was successfully destroyed.'
  end

  private
    def review_params
      params.require(:review).permit(:content, :rating)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.firstname, class: "gravatar")
  end
end

app/views/categories/_form.html.haml
= form_for category do |f|
  - if category.errors.any?
    #error_explanation
      %h2= "#{pluralize(category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

.row
%p
= link_to 'Show', category, class: 'btn btn-default'
\|
= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/index.html.haml
%h1 Categories

.list-group
  - unless user_signed_in? && current_user.admin?
    - categories.each do |category|
      =link_to category, class: 'list-group-item' do
        %span.glyphicon.glyphicon-list
        =category.name
  - else
    - categories.each do |category|
      .list-group-item
        %span.glyphicon.glyphicon-list
        =category.name
        %span.pull-right
          =link_to "Show", category, class: "btn btn-xs btn-success"
          =link_to "Edit", edit_category_path(category), class: "btn btn-xs btn-info"
          =link_to category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-warning" do
            %span.glyphicon.glyphicon-trash

%br
- if user_signed_in? && current_user.admin?
  = link_to 'New Category', new_category_path, class: 'btn btn-default'

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/show.html.haml
.row
  .col-md-3
    %p
      .list-group Categories:
      -categories.each do |c|
        - active_css = category.name == c.name ? "active" : ""
        =link_to c, class: "list-group-item #{active_css}" do
          %span.glyphicon.glyphicon-list
          =c.name
    %input#hideshow{:type => "button", :value => "Add product", :class => 'btn btn-success'}
  .col-md-9
    %p
      .list-group Products:
      - category.products.each do |product|
        = link_to(product.title, category_product_path(category, product), class: 'list-group-item')

.row.col-md-9.col-md-offset-3
  #content{:style => "display: none;", :class => "well well-lg"}
    %p
      %h3 New product
      = render 'products/form'

.row
-if user_signed_in? && current_user.admin?
  =link_to "Edit", edit_category_path(category), class: 'btn btn-default'
  \|
= link_to "Back", categories_path, class: 'btn btn-primary'

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    %nav.navbar.navbar-inverse.navbar-static-top
      .container
        .navbar-header
          = link_to "#{AppConfig.workshops_name }", '/', class: 'navbar-brand'
        %ul.nav.navbar-nav.navbar-right

          - if user_signed_in?
            %li= link_to(current_user.email, user_path(current_user.id))
            %li= link_to("Logout", destroy_user_session_path, method: :delete)
          - else
            %li= link_to("Sign up", new_user_registration_path)
            %li= link_to("Login", new_user_session_path)

    .container
      - if notice
        .alert.alert-info= notice
      - if alert
        .alert.alert-warning= alert
      .row
        .col-md-12
          = yield

app/views/products/_form.html.haml
= form_for [category, product] do |f|
  - if product.errors.any?
    #error_explanation
      %h2= "#{pluralize(product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - product.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .form-group
    = f.label :price
    = f.text_field :price, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', category_product_path(category, product)
\|
= link_to 'Back', category_path(category)

app/views/products/index.html.haml
%h1 Listing products

%table.table
  %tr
    %th Title
    %th Description
    %th Price
    %th
    %th
    %th

  - products.each do |product|
    %tr
      %td= product.title
      %td= product.description
      %td= product.price
      %td= link_to 'Show', category_product_path(product.category, product)
      %td= link_to 'Edit', edit_category_product_path(product.category, product)
      %td= link_to 'Destroy', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', category_products_path

app/views/products/show.html.haml
%h2= "Category #{product.category.name}"
%p
.row
  .col-md-3
    .list-group Products:
    - category.products.each do |p|
      = link_to(p.title, category_product_path(category, p), class: 'list-group-item')
  .col-md-9
    .thumbnail
      %img.img-responsive{:src => "http://placehold.it/800x300"}
      .caption-full
        %h4.pull-right
          %b Price:
          = product.price
        %h4
          %b Title:
          = product.title
        %p
          %b Description:
          = product.description
          %p.pull-right
            %em Avarage rating:
            = product.average_rating
          %p
            %b Category
            = product.category.name
#content{:style => "display: none;", :class => "col-md-9 col-md-offset-3"}
  = render 'reviews/form'
.well.well-sm.col-md-9.col-md-offset-3
  %span.pull-right
    %input#hideshow{:type => "button", :value => "Leave review", :class => 'btn btn-success'}
  %h3 Reviews

  = render reviews

%p
.row.col-md-12
  = link_to 'Edit', edit_category_product_path(category.id, product.id), class: 'btn btn-default'
  \|
  = link_to 'Back', category_path(category), class: 'btn btn-primary'

app/views/reviews/_form.html.haml
= simple_form_for [category, product, review] do |f|
  - if review.errors.any?
    #error_explanation
      %h2= "#{pluralize(review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - review.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control'
  .form-group
    = f.input :rating, collection: 1..5, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default'

app/views/reviews/_rating.html.haml
%p
  - if rating >= 1
    %span.glyphicon.glyphicon-star
  - else
    %span.glyphicon.glyphicon-star-empty

  - if rating >= 2
    %span.glyphicon.glyphicon-star
  - else
    %span.glyphicon.glyphicon-star-empty

  - if rating >= 3
    %span.glyphicon.glyphicon-star
  - else
    %span.glyphicon.glyphicon-star-empty

  - if rating >= 4
    %span.glyphicon.glyphicon-star
  - else
    %span.glyphicon.glyphicon-star-empty

  - if rating >= 5
    %span.glyphicon.glyphicon-star
  - else
    %span.glyphicon.glyphicon-star-empty

  %b= rating

app/views/reviews/_review.html.haml
%p= review.content
%p
  = render partial: 'reviews/rating', :locals => {rating: review.rating}
  %em= review.author

app/views/users/show.html.haml
- provide(:title, @user.email)
.row
  .col-md-4
    %section
      %h2
        = gravatar_for @user
        = "#{@user.firstname} #{@user.lastname}"
      = @user.email
      %p
        Member since #{@user.member_since}
    - if current_user == @user
      =link_to "Edit", edit_user_registration_path, class: 'btn btn-xs btn-default'
  - if @user.reviews.any?
    .col-md-8.well.well-sm
      %h3
        Reviews (#{@user.reviews.count}) - last five:
      - @user.reviews.last(5).reverse.each do |review|
        %p= review.created_at.strftime("%d-%m-%y")
        %p= review.product.title
        %p= review.content
        = render partial: 'reviews/rating', :locals => {rating: review.rating}